course-details :
  - name : "course-name.md"
  - description : "course-description.md"
grading-scale: "grading/grading-scale.csv"
learning-modules :
  - module_01 :
    - name : "MODULE_NAME"
    - location : "modules/module-name/"
    - overview :
      - "module-name.md"
      - "description.md"
      - "learning-objectives.md"
      - "prerequisite-knowledge-and-skills.md"
      - "required-access-materials-or-equipment.md"
    - learning_resources :
      - "content.md"
      - "scaffolding/steps-to-completion.md"
    - assignments :
      - location : "assignments/"
      - Blog post 01 :
        - location : "blog-posts/post-01.md"
        - assessment : "assessment/simple-assignment/"
        - description: "simple-assignment-description.md"
        - rubric : "simple-assignment-rubric.csv"
        - feedback : "simple-assignment-default-feedback.csv"
      - Exercise 01 :
        - location : "exercises/exercise-01.md"
        - assessment : "assessment/simple-assignment/"
        - description: "simple-assignment-description.md"
        - rubric : "simple-assignment-rubric.csv"
        - feedback : "simple-assignment-default-feedback.csv"
      - Project 01 :
        - location : "projects/post-01.md"
        - assessment : "assessment/adaptive-assignment/"
        - description: "adaptive-assignment-description.md"
        - rubric : "adaptive-assignment-rubric.csv"
        - feedback : "adaptive-assignment-default-feedback.csv"
# comments
