course-name : "Course Name"
grading scale: "grading/grading-scale.csv"
learning-modules : 
    - module: "module-name"
        - overview :
            - "module-name.md"
            - "description.md"
            - "learning-objectives.md"
            - "prerequisite-knowledge-and-skills.md"
            - "required-access-materials-or-equipment.md"
        - learning-resources : 
            - "content.md"
            - "scaffolding/steps-to-completion.md"
        - assignments : "assignments/"
            - blog-post-01 : "blog-posts/post-01.md"
                - assessment : "assessment/simple-assignment/"
                    - description: "simple-assignment-description.md"
                    - rubric : "simple-assignment-rubric.csv"
                    - feedback : "simple-assignment-default-feedback.csv"
            - exercise-01 : "exercises/exercise-01.md"
                - assessment : "assessment/simple-assignment/"
                    - description: "simple-assignment-description.md"
                    - rubric : "simple-assignment-rubric.csv"
                    - feedback : "simple-assignment-default-feedback.csv"
            - project-01 : "projects/post-01.md"
                - assessment : "assessment/adaptive-assignment/"
                    - description: "adaptive-assignment-description.md"
                    - rubric : "adaptive-assignment-rubric.csv"
                    - feedback : "adaptive-assignment-default-feedback.csv"
# comments
